version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  webapp:
    image: mvdicarlo/shortener:staging
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
