version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  webapp:
    image: mvdicarlo/shortener:staging
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
